apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Ci-Springboot
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - uses: docker://maven:3.9.5-eclipse-temurin-17-alpine
        name: mvn
        kind: build
        shell: bash
        run: "mvn clean install "
      - name: Scan with SonarQube bundled action
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        env:
          SONAR_SCANNER_OPTS: "sonar.java.binaries=target/classes"
      - name: Set up Docker Hub registry
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: index.docker.io # or docker.io
          username: ${{ vars.ACATERNBERG_DOCKER_USERNAME }}
          password: ${{ secrets.ACATERNBERG_DOCKER_PW }}
      - name: Push image to registry
        uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ vars.ACATERNBERG_DOCKER_USERNAME }}/cb-saas-spring-boot:latest
